In [1]:
import utils

In [2]:
data_devign = utils.load_data("devign.csv")

Load csv...: 28it [00:00, 46.05it/s]

In [3]:
data_devign = utils.merge_function_with_leading_comment(data_devign, key="FunctionWithLeadingComment")
data_devign

Merging Function and Leading Comment...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 27282/27282 [00:00<00:00, 172968.70it/s]

,Projectname,Commit-ID,Filepath,Function,LeadingComment,PS,MAT,Devign,SecI,FunctionWithLeadingComment
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,NaN,static av_cold int vdadec_init(AVCodecContext ...,NaN,0,0,0,True,static av_cold int vdadec_init(AVCodecContext ...
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,NaN,static int transcode(AVFormatContext **output_...,NaN,0,0,0,True,static int transcode(AVFormatContext **output_...
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,NaN,"static void v4l2_free_buffer(void *opaque, uin...",NaN,0,0,0,False,"static void v4l2_free_buffer(void *opaque, uin..."
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,NaN,"int ff_get_wav_header(AVFormatContext *s, AVIO...",NaN,0,0,0,False,"int ff_get_wav_header(AVFormatContext *s, AVIO..."
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,NaN,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",NaN,0,0,0,False,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ..."
...,...,...,...,...,...,...,...,...,...,...
27277,qemu,1ea879e5580f63414693655fcf0328559cdce138,NaN,"static int no_init_in (HWVoiceIn *hw, audsetti...",NaN,0,0,0,False,"static int no_init_in (HWVoiceIn *hw, audsetti..."
27278,qemu,f74990a5d019751c545e9800a3376b6336e77d38,NaN,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",NaN,0,0,0,False,"uint32_t HELPER(stfle)(CPUS390XState *env, uin..."
27279,qemu,a89f364ae8740dfc31b321eed9ee454e996dc3c1,NaN,"static void pxa2xx_fir_write(void *opaque, hwa...",NaN,0,1,0,False,"static void pxa2xx_fir_write(void *opaque, hwa..."
27280,qemu,39fb730aed8c5f7b0058845cb9feac0d4b177985,NaN,"static void disas_thumb_insn(CPUARMState *env,...",NaN,0,0,0,False,"static void disas_thumb_insn(CPUARMState *env,..."
27281,FFmpeg,7104c23bd1a1dcb8a7d9e2c8838c7ce55c30a331,NaN,"static void rv34_pred_mv(RV34DecContext *r, in...",/**\n * motion vector prediction\n *\n * Motio...,0,0,0,False,/**\n * motion vector prediction\n *\n * Motio...

In [4]:
data_devign = utils.extract_comments(data_devign, key = "OnlyComments")
data_devign

Extracting comments...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27282/27282 [00:02<00:00, 12123.85it/s]

,Projectname,Commit-ID,Filepath,Function,LeadingComment,PS,MAT,Devign,SecI,FunctionWithLeadingComment,OnlyComments
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,NaN,static av_cold int vdadec_init(AVCodecContext ...,NaN,0,0,0,True,static av_cold int vdadec_init(AVCodecContext ...,/* init pix_fmts of codec */ /* init vda */ /*...
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,NaN,static int transcode(AVFormatContext **output_...,NaN,0,0,0,True,static int transcode(AVFormatContext **output_...,/* output stream init */ /* Sanity check the m...
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,NaN,"static void v4l2_free_buffer(void *opaque, uin...",NaN,0,0,0,False,"static void v4l2_free_buffer(void *opaque, uin...",
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,NaN,"int ff_get_wav_header(AVFormatContext *s, AVIO...",NaN,0,0,0,False,"int ff_get_wav_header(AVFormatContext *s, AVIO...",/* We're dealing with plain vanilla WAVEFORMAT...
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,NaN,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",NaN,0,0,0,False,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",
...,...,...,...,...,...,...,...,...,...,...,...
27277,qemu,1ea879e5580f63414693655fcf0328559cdce138,NaN,"static int no_init_in (HWVoiceIn *hw, audsetti...",NaN,0,0,0,False,"static int no_init_in (HWVoiceIn *hw, audsetti...",
27278,qemu,f74990a5d019751c545e9800a3376b6336e77d38,NaN,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",NaN,0,0,0,False,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",
27279,qemu,a89f364ae8740dfc31b321eed9ee454e996dc3c1,NaN,"static void pxa2xx_fir_write(void *opaque, hwa...",NaN,0,1,0,False,"static void pxa2xx_fir_write(void *opaque, hwa...",/* RXE */ /* TXE */ /* Nop */ /* ITR */ /* TXP...
27280,qemu,39fb730aed8c5f7b0058845cb9feac0d4b177985,NaN,"static void disas_thumb_insn(CPUARMState *env,...",NaN,0,0,0,False,"static void disas_thumb_insn(CPUARMState *env,...",/* Skip conditional when condition is AL. */ /...
27281,FFmpeg,7104c23bd1a1dcb8a7d9e2c8838c7ce55c30a331,NaN,"static void rv34_pred_mv(RV34DecContext *r, in...",/**\n * motion vector prediction\n *\n * Motio...,0,0,0,False,/**\n * motion vector prediction\n *\n * Motio...,/**\n * motion vector prediction\n *\n * Motio...

In [5]:
data_devign = utils.has_comments(data_devign, key = "hasComments")
data_devign

Extracting if a function contains a comment...: 100%|███████████████████████████████████████████████████████████████████████████████████████| 27282/27282 [00:02<00:00, 12218.65it/s]

,Projectname,Commit-ID,Filepath,Function,LeadingComment,PS,MAT,Devign,SecI,FunctionWithLeadingComment,OnlyComments,hasComments
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,NaN,static av_cold int vdadec_init(AVCodecContext ...,NaN,0,0,0,True,static av_cold int vdadec_init(AVCodecContext ...,/* init pix_fmts of codec */ /* init vda */ /*...,True
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,NaN,static int transcode(AVFormatContext **output_...,NaN,0,0,0,True,static int transcode(AVFormatContext **output_...,/* output stream init */ /* Sanity check the m...,True
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,NaN,"static void v4l2_free_buffer(void *opaque, uin...",NaN,0,0,0,False,"static void v4l2_free_buffer(void *opaque, uin...",,False
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,NaN,"int ff_get_wav_header(AVFormatContext *s, AVIO...",NaN,0,0,0,False,"int ff_get_wav_header(AVFormatContext *s, AVIO...",/* We're dealing with plain vanilla WAVEFORMAT...,True
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,NaN,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",NaN,0,0,0,False,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",,False
...,...,...,...,...,...,...,...,...,...,...,...,...
27277,qemu,1ea879e5580f63414693655fcf0328559cdce138,NaN,"static int no_init_in (HWVoiceIn *hw, audsetti...",NaN,0,0,0,False,"static int no_init_in (HWVoiceIn *hw, audsetti...",,False
27278,qemu,f74990a5d019751c545e9800a3376b6336e77d38,NaN,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",NaN,0,0,0,False,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",,False
27279,qemu,a89f364ae8740dfc31b321eed9ee454e996dc3c1,NaN,"static void pxa2xx_fir_write(void *opaque, hwa...",NaN,0,1,0,False,"static void pxa2xx_fir_write(void *opaque, hwa...",/* RXE */ /* TXE */ /* Nop */ /* ITR */ /* TXP...,True
27280,qemu,39fb730aed8c5f7b0058845cb9feac0d4b177985,NaN,"static void disas_thumb_insn(CPUARMState *env,...",NaN,0,0,0,False,"static void disas_thumb_insn(CPUARMState *env,...",/* Skip conditional when condition is AL. */ /...,True
27281,FFmpeg,7104c23bd1a1dcb8a7d9e2c8838c7ce55c30a331,NaN,"static void rv34_pred_mv(RV34DecContext *r, in...",/**\n * motion vector prediction\n *\n * Motio...,0,0,0,False,/**\n * motion vector prediction\n *\n * Motio...,/**\n * motion vector prediction\n *\n * Motio...,True

In [6]:
data_devign = utils.remove_comments(data_devign, key = "OnlyFunction")
data_devign

Removing comments from function...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 27282/27282 [00:02<00:00, 11693.72it/s]

,Projectname,Commit-ID,Filepath,Function,LeadingComment,PS,MAT,Devign,SecI,FunctionWithLeadingComment,OnlyComments,hasComments,OnlyFunction
0,FFmpeg,973b1a6b9070e2bf17d17568cbaf4043ce931f51,NaN,static av_cold int vdadec_init(AVCodecContext ...,NaN,0,0,0,True,static av_cold int vdadec_init(AVCodecContext ...,/* init pix_fmts of codec */ /* init vda */ /*...,True,static av_cold int vdadec_init(AVCodecContext ...
1,FFmpeg,321b2a9ded0468670b7678b7c098886930ae16b2,NaN,static int transcode(AVFormatContext **output_...,NaN,0,0,0,True,static int transcode(AVFormatContext **output_...,/* output stream init */ /* Sanity check the m...,True,static int transcode(AVFormatContext **output_...
2,FFmpeg,5d5de3eba4c7890c2e8077f5b4ae569671d11cf8,NaN,"static void v4l2_free_buffer(void *opaque, uin...",NaN,0,0,0,False,"static void v4l2_free_buffer(void *opaque, uin...",,False,"static void v4l2_free_buffer(void *opaque, uin..."
3,FFmpeg,32bf6550cb9cc9f487a6722fe2bfc272a93c1065,NaN,"int ff_get_wav_header(AVFormatContext *s, AVIO...",NaN,0,0,0,False,"int ff_get_wav_header(AVFormatContext *s, AVIO...",/* We're dealing with plain vanilla WAVEFORMAT...,True,"int ff_get_wav_header(AVFormatContext *s, AVIO..."
4,FFmpeg,57d77b3963ce1023eaf5ada8cba58b9379405cc8,NaN,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",NaN,0,0,0,False,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ...",,False,"int av_opencl_buffer_write(cl_mem dst_cl_buf, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27277,qemu,1ea879e5580f63414693655fcf0328559cdce138,NaN,"static int no_init_in (HWVoiceIn *hw, audsetti...",NaN,0,0,0,False,"static int no_init_in (HWVoiceIn *hw, audsetti...",,False,"static int no_init_in (HWVoiceIn *hw, audsetti..."
27278,qemu,f74990a5d019751c545e9800a3376b6336e77d38,NaN,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",NaN,0,0,0,False,"uint32_t HELPER(stfle)(CPUS390XState *env, uin...",,False,"uint32_t HELPER(stfle)(CPUS390XState *env, uin..."
27279,qemu,a89f364ae8740dfc31b321eed9ee454e996dc3c1,NaN,"static void pxa2xx_fir_write(void *opaque, hwa...",NaN,0,1,0,False,"static void pxa2xx_fir_write(void *opaque, hwa...",/* RXE */ /* TXE */ /* Nop */ /* ITR */ /* TXP...,True,"static void pxa2xx_fir_write(void *opaque, hwa..."
27280,qemu,39fb730aed8c5f7b0058845cb9feac0d4b177985,NaN,"static void disas_thumb_insn(CPUARMState *env,...",NaN,0,0,0,False,"static void disas_thumb_insn(CPUARMState *env,...",/* Skip conditional when condition is AL. */ /...,True,"static void disas_thumb_insn(CPUARMState *env,..."
27281,FFmpeg,7104c23bd1a1dcb8a7d9e2c8838c7ce55c30a331,NaN,"static void rv34_pred_mv(RV34DecContext *r, in...",/**\n * motion vector prediction\n *\n * Motio...,0,0,0,False,/**\n * motion vector prediction\n *\n * Motio...,/**\n * motion vector prediction\n *\n * Motio...,True,"static void rv34_pred_mv(RV34DecContext *r, in..."

In [7]:
#data_devign.to_csv("./devign_annotated.csv", index=False)